apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ms-order
  name: ms-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-order
  strategy: {}
  template:
    metadata:
      labels:
        app: ms-order
    spec:
      containers:
        - image: tarrupe/ms-practical-ws
          name: ms-order
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: SERVICE_NAME
              value: "order"
            - name: POSTGRES_HOST
              value: "postgres.default.svc.cluster.local"
            - name: POSTGRES_DB
              value: "ms_order_dev"
            - name: AMQP_URI
              value: "amqp://app:password@rabbitmq.default.svc.cluster.local:5672"
            - name: OTLP_COLLECTOR
              value: "http://otel-collector-daemonset-collector:4318/v1/traces"
            - name: LOKI_HOST
              value: "http://loki-stack:3100"
          command: ["/bin/sh"]
          args: ["-c", "node -r './dist/infra/tracing.js' dist/order/server.js"]
          resources: {}
status: {}
