apiVersion: v1
kind: Service
metadata:
  name: ms-order
  labels:
    app.kubernetes.io/name: ms-order
    app.kubernetes.io/instance: ms-order
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: ms-order
